// Code generated by hack/meta-generate.sh. DO NOT EDIT.
//go:generate mockgen -package git -destination mocks.go github.com/trishanku/gitcd/pkg/git Blob,Commit,CommitWalker,Interface,Object,ObjectConverter,ObjectGetter,ObjectReceiver,Peelable,Peeler,Reference,ReferenceCollection,Repository,Tree,TreeEntry,TreeWalker
package git
