apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

namespace: trishanku
commonLabels:
  app: trishanku
  component: kube-apiserver

resources:
- certificate.yaml
- issuer.yaml

patchesStrategicMerge:
- deployment_patch.yaml

configurations:
- kustomizeconfig.yaml

vars:
- name: APISERVER_SERVICE_NAMESPACE
  objref:
    kind: Service
    version: v1
    name: kube-apiserver
  fieldref:
    fieldpath: metadata.namespace
- name: APISERVER_SERVICE_NAME
  objref:
    kind: Service
    version: v1
    name: kube-apiserver