apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-apiserver
spec:
  template:
    spec:
      containers:
      - name: kube-apiserver
        image: k8s.gcr.io/kube-apiserver:v1.23.2
        imagePullPolicy: IfNotPresent

    