name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    
    - name: Login to GAR
      uses: docker/login-action@v2
      with:
        registry: asia-south1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GAR_JSON_KEY }}
          
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        images: trishanku/gitcd
        tags: type=sha
