apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitcd
spec:
  dnsNames:
  - $(SERVICE_NAME)
  - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
  - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.cluster.local
  issuerRef:
    kind: Issuer
    name: gitcd
  secretName: gitcd
