apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

namespace: trishanku
commonLabels:
  app: trishanku
  component: gitcd

resources:
- certificate.yaml
- issuer.yaml

patchesStrategicMerge:
- statefulset_patch.yaml

configurations:
- kustomizeconfig.yaml

vars:
- name: GITCD_SERVICE_NAMESPACE
  objref:
    kind: Service
    version: v1
    name: gitcd
  fieldref:
    fieldpath: metadata.namespace
- name: GITCD_SERVICE_NAME
  objref:
    kind: Service
    version: v1
    name: gitcd