apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitcd
spec:
  serviceName: gitcd
  template:
    spec:
      initContainers:
      - name: git-init
        image: bitnami/git:2
        imagePullPolicy: IfNotPresent
        command:
        - git
        - init
        - --initial-branch=main
        workingDir: /tmp/trishanku/gitcd
        volumeMounts:
        - name: repo
          mountPath: /tmp/trishanku/gitcd
      - name: git-commit
        image: bitnami/git:2
        imagePullPolicy: IfNotPresent
        command:
        - git
        - commit
        - --message=Init
        - --allow-empty
        workingDir: /tmp/trishanku/gitcd
        volumeMounts:
        - name: repo
          mountPath: /tmp/trishanku/gitcd
      - name: gitcd-init
        image: localhost:6000/trishanku/gitcd
        imagePullPolicy: Always
        args:
        - init
        volumeMounts:
        - name: repo
          mountPath: /tmp/trishanku/gitcd
      containers:
      - name: gitcd
        image: localhost:6000/trishanku/gitcd
        imagePullPolicy: Always
        args:
        - serve
        - --advertise-client-urls=default=http://gitcd:2379/
        - --debug
        volumeMounts:
        - name: repo
          mountPath: /tmp/trishanku/gitcd
      volumes:
      - name: repo
        emptyDir: {}

    