kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: trishanku
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        etcd-compaction-interval: "0"
        etcd-servers-overrides: "/events#http://192.168.1.11:2379"
        # max-requests-inflight: "0"
        # max-mutating-requests-inflight: "0"
        storage-media-type: application/yaml
        # watch-cache: "false"
    etcd:
      external:
        endpoints:
        - http://192.168.1.11:2479
      local: ~
    timeoutForControlPlane: 10m
