kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: trishanku
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    etcd:
      external:
        endpoints:
        - "http://192.168.1.6:2379/"
      local: ~
