apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:2
    imagePullPolicy: IfNotPresent
status:
  phase: Scheduled
  conditions:
  - type: MemoryPressure
    status: False
    message: "Pod has sufficient memory"
